-- 用户反馈表
CREATE TABLE `DI_FEEDBACK` (
  `ID` char(32) NOT NULL COMMENT '主键',
  `ORDER_ID` varchar(200) DEFAULT NULL COMMENT '订单ID',
  `USER_ID` varchar(200) DEFAULT NULL COMMENT '用户ID',
  `USER_COMMENT` varchar(200) NOT NULL COMMENT '用户评论',
  `CREATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `IS_DELETED` int(11) DEFAULT '0' COMMENT '0未删除1删除',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ORDER_ID_UNIQUE` (`ORDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 订单表
CREATE TABLE `DI_ORDER` (
  `ID` char(32) NOT NULL COMMENT '主键',
  `ORDER_ID` varchar(200) DEFAULT NULL COMMENT '订单ID',
  `USER_ID` varchar(200) DEFAULT NULL COMMENT '用户ID',
  `OERDER_STATE` varchar(200) DEFAULT '1' COMMENT '(1, "创建订单"),(2,"确认订单"),(3,"取消订单"),(4, "完成订单")',
  `PHONE` varchar(200) DEFAULT NULL COMMENT '联系人手机号',
  `ADDRESS` varchar(200) DEFAULT NULL COMMENT '下单地址',
  `TARGET_ADDRESS` varchar(200) DEFAULT NULL COMMENT '目标地址',
  `TARGET_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '目标送达时间',
  `ORDER_INFO` varchar(200) DEFAULT NULL COMMENT '订单信息',
  `TOTAL_ACCOUNT` int(11) DEFAULT NULL COMMENT '费用',
  `CREATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `FINISH_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '完成时间',
  `IS_DELETED` int(11) DEFAULT '0' COMMENT '0未删除1删除',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ORDER_ID_UNIQUE` (`ORDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- 用户表
CREATE TABLE `DI_USER` (
  `ID` char(32) NOT NULL COMMENT '主键',
  `NAME` varchar(200) NOT NULL COMMENT '用户姓名',
  `AGE` int(11) NOT NULL COMMENT '年龄',
  `GENDER` int(11) DEFAULT NULL COMMENT '性别',
  `ADDRES` varchar(200) DEFAULT NULL COMMENT '用户地址',
  `PHONE` varchar(200) NOT NULL COMMENT '用户手机号',
  `LOGIN_NAME` varchar(200) NOT NULL COMMENT '登录名',
  `PASSWORD` varchar(200) NOT NULL COMMENT '登录密码',
  `USER_ID` varchar(200) NOT NULL COMMENT '用户ID',
  `CREATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `IS_DELETED` int(11) DEFAULT '0' COMMENT '0未删除1删除',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_ID_UNIQUE` (`USER_ID`),
  UNIQUE KEY `LOGIN_NAME_UNIQUE` (`LOGIN_NAME`),
  UNIQUE KEY `PHONE_UNIQUE` (`PHONE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
